CREATE TABLE Players (
    person_id BIGINT PRIMARY KEY, 
    firstName VARCHAR(50),
    lastName VARCHAR(100),
    birthDate DATE,
    school VARCHAR(100),
    country VARCHAR(100),
    height_inches DECIMAL(5,2),
    body_weight_lba DECIMAL(5,2),
    guard SMALLINT,
    forward SMALLINT,
    center SMALLINT,
    draft_year SMALLINT,
    draft_round SMALLINT,
    draft_number SMALLINT
);

CREATE TABLE player_game_stats(
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    person_id BIGINT REFERENCES players(person_id),
    game_id BIGINT,
    game_datetime TIMESTAMP,
    player_team_city VARCHAR(100),
    player_team_name VARCHAR(100),
    opponent_team_city VARCHAR(100),
    opponent_team_name VARCHAR(100),
    game_type VARCHAR(50),
    win SMALLINT, 
    home SMALLINT,
    num_minutes DECIMAL(6,2),
    points DECIMAL(6,2),
    assists DECIMAL(6,2),
    blocks DECIMAL(6,2),
    steals DECIMAL(6,2),
    field_goals_attempted DECIMAL(6,2),
    field_goals_made DECIMAL(6,2),
    field_goals_percentage DECIMAL(5,3),
    three_pointers_attempted DECIMAL(6,2),
    three_pointers_made DECIMAL(6,2),
    three_pointers_percentage DECIMAL(5,3),
    free_throws_attempted DECIMAL(6,2),
    free_throws_made DECIMAL(6,2),
    free_throws_percentage DECIMAL(5,3),
    rebounds_defensive DECIMAL(6,2),
    rebounds_offensive DECIMAL(6,2),
    rebounds_total DECIMAL(6,2),
    fouls_personal DECIMAL(6,2),
    turnovers DECIMAL(6,2),
    plus_minus_points DECIMAL(6,2)
);